# GoReleaser configuration for Orla
# See https://goreleaser.com for documentation

version: 2

project_name: orla

builds:
  - id: orla
    main: ./cmd/orla
    binary: orla
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildDate={{.Date}}

# Create archives for Homebrew formula (brews needs archives to reference)
# The install script will still be used, but brews needs archives for the formula
archives:
  - id: default
    builds:
      - orla
    name_template: >-
      {{- if eq .Os "linux" -}}
        orla-linux-{{ .Arch }}
      {{- else if eq .Os "darwin" -}}
        orla-darwin-{{ .Arch }}
      {{- else -}}
        orla-{{ .Os }}-{{ .Arch }}
      {{- end -}}
    formats:
      - tar.gz

# Sign and notarize macOS binaries using cross-platform method (quill)
# This works on any OS and handles both signing and notarization
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - orla
      # Sign the binaries before notarization
      sign:
        # The base64 encoded .p12 certificate
        certificate: '{{ .Env.MACOS_SIGN_P12 }}'
        # Password to unlock the certificate
        password: '{{ .Env.MACOS_SIGN_PASSWORD }}'
        # Developer ID Application identity (auto-detected from certificate)
      # Notarize using App Store Connect API
      notarize:
        # Whether to wait for notarization to complete
        wait: true
        # Timeout for notarization
        timeout: 20m
        # App Store Connect API credentials
        key: '{{ .Env.MACOS_NOTARY_KEY }}'
        key_id: '{{ .Env.MACOS_NOTARY_KEY_ID }}'
        issuer_id: '{{ .Env.MACOS_NOTARY_ISSUER_ID }}'

# Publish to GitHub releases
release:
  github:
    owner: dorcha-inc
    name: orla
  draft: false
  mode: replace
  header: |
    ## Orla {{ .Tag }}
    
    Release {{ .Tag }} of Orla.
  footer: |
    ---
    
    Full Changelog: https://github.com/dorcha-inc/orla/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew cask configuration
homebrew_casks:
  - name: orla
    # Use the same repository - the cask will be in the Casks/ directory
    repository:
      owner: dorcha-inc
      name: orla
      # Use GITHUB_TOKEN (default GitHub Actions token) since we're pushing to the same repo
      token: "{{ .Env.GITHUB_TOKEN }}"
    
    # The commit author
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    
    # The homepage for the project
    homepage: "https://github.com/dorcha-inc/orla"
    
    # A description for the project
    description: "A dead-simple unix tool for lightweight agents"

    # The license of the project
    license: "MIT"
    
    # Binary name (the executable inside the archive)
    binaries:
      - orla
    
    # Use hooks to run the install script for post-install setup (Ollama + model)
    # Homebrew installs the binary, then we run the install script with --homebrew flag
    hooks:
      post:
        install: |
          system "/bin/sh", "-c", "curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew"

# Generate checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Changelog configuration
changelog:
  sort: asc

