# Codecov configuration for orla
# See https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: false

coverage:
  # Exclude cmd/ (CLI applications) and examples (demonstration code)
  # Using "folder/" pattern ignores the folder and all its contents recursively
  ignore:
    - "cmd/"
    - "examples/"

  # Status settings
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
