// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completion_io.sql

package db

import (
	"context"
)

const completionIOByWorkflowRun = `-- name: CompletionIOByWorkflowRun :many
SELECT completion_id, workflow_run, stage_id, request_content, response_content, created_at
FROM completion_io
WHERE workflow_run = $1
ORDER BY created_at
`

// Captured request and response content for every captured stage of one
// workflow run, in stage order. Written only for stages with capture_io on.
func (q *Queries) CompletionIOByWorkflowRun(ctx context.Context, workflowRun *string) ([]CompletionIo, error) {
	rows, err := q.db.Query(ctx, completionIOByWorkflowRun, workflowRun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompletionIo{}
	for rows.Next() {
		var i CompletionIo
		if err := rows.Scan(
			&i.CompletionID,
			&i.WorkflowRun,
			&i.StageID,
			&i.RequestContent,
			&i.ResponseContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
