// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mapping_variants.sql

package db

import (
	"context"
)

const deleteVariant = `-- name: DeleteVariant :execrows
DELETE FROM mapping_variants WHERE name = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariant, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMappingOverride = `-- name: GetMappingOverride :one
SELECT backend
FROM mapping_variants
WHERE name = $1 AND stage_id = $2
`

type GetMappingOverrideParams struct {
	Name    string
	StageID string
}

// The backend override for one (variant, stage). No row means the
// request falls through to the stage's live backend.
func (q *Queries) GetMappingOverride(ctx context.Context, arg GetMappingOverrideParams) (string, error) {
	row := q.db.QueryRow(ctx, getMappingOverride, arg.Name, arg.StageID)
	var backend string
	err := row.Scan(&backend)
	return backend, err
}

const listAllVariantOverrides = `-- name: ListAllVariantOverrides :many
SELECT name, stage_id, backend, created_at, updated_at
FROM mapping_variants
ORDER BY name, stage_id
`

// Every override across all variants, ordered so a caller can group
// consecutive rows by name.
func (q *Queries) ListAllVariantOverrides(ctx context.Context) ([]MappingVariant, error) {
	rows, err := q.db.Query(ctx, listAllVariantOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MappingVariant{}
	for rows.Next() {
		var i MappingVariant
		if err := rows.Scan(
			&i.Name,
			&i.StageID,
			&i.Backend,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantOverrides = `-- name: ListVariantOverrides :many
SELECT name, stage_id, backend, created_at, updated_at
FROM mapping_variants
WHERE name = $1
ORDER BY stage_id
`

// All overrides for one variant, ordered by stage id.
func (q *Queries) ListVariantOverrides(ctx context.Context, name string) ([]MappingVariant, error) {
	rows, err := q.db.Query(ctx, listVariantOverrides, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MappingVariant{}
	for rows.Next() {
		var i MappingVariant
		if err := rows.Scan(
			&i.Name,
			&i.StageID,
			&i.Backend,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMappingOverride = `-- name: UpsertMappingOverride :exec
INSERT INTO mapping_variants (name, stage_id, backend)
VALUES ($1, $2, $3)
ON CONFLICT (name, stage_id) DO UPDATE
SET backend = EXCLUDED.backend,
    updated_at = now()
`

type UpsertMappingOverrideParams struct {
	Name    string
	StageID string
	Backend string
}

func (q *Queries) UpsertMappingOverride(ctx context.Context, arg UpsertMappingOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertMappingOverride, arg.Name, arg.StageID, arg.Backend)
	return err
}
