// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler_policy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSchedulerPolicy = `-- name: GetSchedulerPolicy :one
SELECT url, timeout_ms, updated_at
FROM scheduler_policy
WHERE id = true
`

type GetSchedulerPolicyRow struct {
	Url       string
	TimeoutMs int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetSchedulerPolicy(ctx context.Context) (GetSchedulerPolicyRow, error) {
	row := q.db.QueryRow(ctx, getSchedulerPolicy)
	var i GetSchedulerPolicyRow
	err := row.Scan(&i.Url, &i.TimeoutMs, &i.UpdatedAt)
	return i, err
}

const upsertSchedulerPolicy = `-- name: UpsertSchedulerPolicy :exec
INSERT INTO scheduler_policy (id, url, timeout_ms, updated_at)
VALUES (true, $1, $2, now())
ON CONFLICT (id) DO UPDATE
SET url = EXCLUDED.url,
    timeout_ms = EXCLUDED.timeout_ms,
    updated_at = now()
`

type UpsertSchedulerPolicyParams struct {
	Url       string
	TimeoutMs int32
}

func (q *Queries) UpsertSchedulerPolicy(ctx context.Context, arg UpsertSchedulerPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertSchedulerPolicy, arg.Url, arg.TimeoutMs)
	return err
}
