# This file was generated by GoReleaser. DO NOT EDIT.
cask "orla" do
  name "orla"
  desc "A dead-simple unix tool for lightweight agents"
  homepage "https://github.com/dorcha-inc/orla"
  version "0.3.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orla"

  on_macos do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-amd64.tar.gz"
      sha256 "5a1b61aaac1273fc9c7be9b57ca74e86dfc0be6c628a36d563b8bfa27fab5834"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-arm64.tar.gz"
      sha256 "ccf34bc7a02ec91a66644cdd01ab033f2289b886b9332e323d2ea82fb0cff96a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-amd64.tar.gz"
      sha256 "c57b10eb4775c0b2a69f1b0a74969a0b9775e634386575de3071f62480834cbc"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-arm64.tar.gz"
      sha256 "4fb54459c10b5e0817ffc2e080ace11c77d56393dabea31009c94f3d94ad9668"
    end
  end

  postflight do
    system "/bin/sh", "-c", "curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew"
  end

  # No zap stanza required
end
